### ISSUE TITLE
Error in sc.run_and_plot() in spatial_compare_examples.ipynb

### ISSUE THREAD

**Issue by kandarpRJ** [AllenInstitute/spatial_compare#19]
Hi,

Getting this error after running sc.run_and_plot() 

/opt/anaconda3/envs/spatial/lib/python3.12/site-packages/spatial_compare/spatial_compare.py:172: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(markerscale=5)
/opt/anaconda3/envs/spatial/lib/python3.12/site-packages/spatial_compare/spatial_compare.py:184: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(markerscale=5)
/opt/anaconda3/envs/spatial/lib/python3.12/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/opt/anaconda3/envs/spatial/lib/python3.12/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/opt/anaconda3/envs/spatial/lib/python3.12/site-packages/numpy/lib/function_base.py:2889: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/opt/anaconda3/envs/spatial/lib/python3.12/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/opt/anaconda3/envs/spatial/lib/python3.12/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[27], line 1
----> 1 sc.run_and_plot(category_values = d1d2_cells, min_mean_expression=.2)

File /opt/anaconda3/envs/spatial/lib/python3.12/site-packages/spatial_compare/spatial_compare.py:372, in SpatialCompare.run_and_plot(self, **kwargs)
    369     self.set_category(kwargs["category"])
    371 self.spatial_plot()
--> 372 self.spatial_compare_results = self.spatial_compare(plot_stuff=True, **kwargs)
    373 self.plot_detection_ratio(self.spatial_compare_results["expression_results"]["gene_ratio_dataframe"],figsize=[30,20])
    374 return True

File /opt/anaconda3/envs/spatial/lib/python3.12/site-packages/spatial_compare/spatial_compare.py:360, in SpatialCompare.spatial_compare(self, **kwargs)
    354 ce_kwargs = {key:kwargs[key] for key in inspect.signature(SpatialCompare.compare_expression).parameters.keys()if key in kwargs.keys() and key != "category_values"}
    356 match_results = self.find_matched_groups(
    357                                 **fmr_kwargs)
--> 360 expression_results = self.compare_expression(
    361                category_values=match_results["category_top_values"],
    362                **ce_kwargs
    363               )
    364 match_results["expression_results"] = expression_results
    365 return match_results

File /opt/anaconda3/envs/spatial/lib/python3.12/site-packages/spatial_compare/spatial_compare.py:269, in SpatialCompare.compare_expression(self, category_values, plot_stuff, min_mean_expression, min_genes_to_compare, min_cells)
    264 def compare_expression(self, category_values=[], plot_stuff=False,
    265                   min_mean_expression=.2,
    266                   min_genes_to_compare =5, min_cells = 10):
    267     # group cells
    268     if len(category_values)==0:
--> 269         raise ValueError("please supply a list of values for the category "+self.category)
    272     category_records=[]
    273     gene_ratio_dfs = {}

ValueError: please supply a list of values for the category matched_leiden_clusters

Running the function before sc.de_novo_cluster() works fine but after throws this error.

**Comment by berl** [comment]
closed with #28
